[project]
name = "dicomcriterion"
version = "0.1.0"
description = "Create and evaluate boolean expressions against DICOM datasets"
readme = "README.md"
licence = "MIT"
requires-python = ">=3.10"
dependencies = [
    "boolean.py>=4.0",
    "pydicom>=2.4.0",
    "pytest>=8.4.1",
]
